name: Build Demo

on:
  push:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache mathlib
        id: cache-mathlib
        uses: actions/cache@v4
        with:
          path: vendor
          key: mathlib-v1.0.0-windows   # 版本号变了,这个 key 也要变,才会触发重新下载

        -name: Fetch dependencies (Windows)
        if: matrix.os == 'windows-latest' && steps.cache-mathlib.outputs.cache-hit != 'true'
        run: .\scripts\fetch_deps.ps1

      - name: Fetch dependencies (Linux)
        if: matrix.os == 'ubuntu-latest' && steps.cache-mathlib.outputs.cache-hit != 'true'
        run: ./scripts/fetch_deps.sh

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 'b2f068faf45a3f04145bec0f52a66526ad590227'

      - name: Configure
        run: >
          cmake -B build
          -DMATHLIB_ROOT="${{ github.workspace }}/vendor"
          -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake"

      - name: Build
        run: cmake --build build --config Debug

      - name: Test
        run: ctest --test-dir build -C Debug --output-on-failure

